[platformio]
build_dir = C:\Users\thaol\.pio-build\heritech_robot

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 9600
lib_deps =
    arduino-libraries/ArduinoBLE@^1.3.6
